### ISSUE TITLE
Mudar CI para que warnings impeçam PR

### ISSUE THREAD

**Issue by rafaeleiki** [rafaeleiki/upa-ic#8]
Atualmente, as GitHub Actions que fazem build (`Deploy` e `Check PR`) ignoram os warnings para fins de build. Isso foi feito para conseguir priorizar o término do projeto para a UPA 2021.

Por questões de melhoria da qualidade de código e acessibilidade, isso deve ser mudado no futuro. Para isso, nos arquivos `.github/workflows/deploy.yml` e .`github/workflows/pr-check.yml`, deve ser removido o `CI=""` na seção de build:

```
- name: Building project
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
      env:
        CI: ''   # <-- Aqui!
```

Ficando:
```
- name: Building project
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
```

Isso acarretará em warnings que não vão ser ignorados. Esses warnings deverão ser corrigidos.
